### ISSUE TITLE
OPENSSL_1.0.0

### ISSUE THREAD

**Issue by verres630** [fpw/avitab#10]
I have problem loading this plugin in Arch Linux System:
`symbol SSLv3_client_method version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference`

SSLv3 support was dropped some time ago and is considered unsafe now. I think this plugin needs to be upgraded to TLS.

**Comment by fpw** [comment]
Please try replacing AviTab.xpl in the lin_x64 folder with the following version: http://folko.solhost.org/avitab/AviTab-0.2.3-linux.zip

Does that fix the issue? It now includes static versions of mbedtls, curl, libgeotiff and libtiff and only depends on a few very common (hopefully) shared libraries now.

**Comment by verres630** [comment]
With this new version I have another error:
`dlerror:libjbig.so.0: cannot open shared object file: No such file or directory`

**Comment by verres630** [comment]
Version 0.2.4 working fine in Linux. Thank you for fast response and for your effort to create this fantastic plugin. This issue can be closed now.
