### ISSUE TITLE
Feature: Show course for all runways

### ISSUE THREAD

**Issue by oobayly** [fpw/avitab#105]
Currently, the course is only shown for a runway if there is an ILS. This can cause confusion for offset ILSs, [BIAR](http://www.fly-sea.com/charts/BIAR.pdf) has a ~25° offset, which could ruin one's day!

I've modified the runway generation to include the runway heading, and to output the course, as well as the ILS course if they differ:
EGCC - Manchester Intl - no offset ILS:
![image](https://user-images.githubusercontent.com/3430117/141146576-54abb9cc-74dc-43f6-a816-95c4034e07bb.png)

BIAR - Akureyri - offset ILS (ignore the fact the courses are incorrect, the standalone doesn't appear to calculate the magnetic variation):
![image](https://user-images.githubusercontent.com/3430117/141146836-3d9349e3-5bf4-4b99-8e17-e777b34bc102.png)

Comments would be appreciated.

![image](https://user-images.githubusercontent.com/3430117/141145319-7e2178e0-9e6b-4c96-8cd3-7c4f29d79da2.png)

**Comment by fpw** [comment]
That's a great idea. I'm not a real pilot and hardly fly IFR, so I'm not sure how it's supposed to be and will simply trust your judgement.  Tell me if you need any help getting the data into the GUI.

Thanks!

**Comment by fpw** [comment]
PS: It's correct that the standalone version doesn't have magnetic variation. X-Plane doesn't export its correction data so I can't replicate the SDK call in the standalone version.

**Comment by oobayly** [comment]
> so I'm not sure how it's supposed to be and will simply trust your judgement

Hmm, I'm not sure you really want to do that! :scream: But I can't see any issues arising from this, it should just mean that we have consistent information for all runways.

The main reason I suggested it is that I like to set the CDI needle regardless of whether there's an ILS approach, and this way I can set it accurately.

**Comment by fpw** [comment]
Thanks, integrated!
