### ISSUE TITLE
Feature: Allow Navigraph and ChartFox to be used side-by-side

### ISSUE THREAD

**Issue by oobayly** [fpw/avitab#106]
As it stands, the Airports app only toggles between the airport info and the either Navigraph _or_ ChartFox. Even though I subscribe to Navigraph, there are times when I'd like to use the AIP charts provided by ChartFox as well.

A solution would be to modify the `ChartService` to allow it to be used with multiple providers concurrently, and to update the AirportApp to use multiple sources (eg. multiple buttons). This could tie in with #66 where the ChartService could then be used to source charts from the `charts` path.

Tasks:
- [ ] Add enum to ChartService
- [ ] Add parameters to `getChartsFor`, ~~`loadChart`~~, etc to specify which service is being used
- [ ] Change the behaviour of the AirportApp chart toggle button to multiple buttons.

**Comment by oobayly** [comment]
:facepalm: When I started looking at the code I realised that you *can* use Navigraph and ChartFox concurrently.

**Comment by fpw** [comment]
Thanks for checking back. Could that be a hidden usability problem, i.e. do you have any idea how to make it more clear that it's possible to use both? UX and UI are my weak spots :(

**Comment by oobayly** [comment]
> UX and UI are my weak spots :(

Same here. I think my problem was that when I first enabled ChartFox I chose an airport that had a tonne of procedures so the ones recognised (Navigraph) were at the top of the list, and I didn't see ChartFox ones further down. Most _normal_ people would have simply scrolled down instead of thinking _"how can I fix this"_ and filing a feature request...
