### ISSUE TITLE
Error loading library with macOS High Sierra

### ISSUE THREAD

**Issue by ahmadworks** [fpw/avitab#11]
It doesn't load in mac, this line found on log file.

By the way, I don't have /opt/local/lib directory on my macOS Hight Sierra.

dlerror:dlopen(/Users/ahmad/Library/Application Support/Steam/steamapps/common/X-Plane 11/Resources/plugins/AviTab/mac_x64/AviTab.xpl, 6): Library not loaded: /opt/local/lib/libcurl.4.dylib
  Referenced from: /Users/ahmad/Library/Application Support/Steam/steamapps/common/X-Plane 11/Resources/plugins/AviTab/mac_x64/AviTab.xpl
  Reason: Incompatible library version: AviTab.xpl requires version 10.0.0 or later, but libcurl.4.dylib provides version 7.0.0

**Comment by fpw** [comment]
Thanks for the report. Please try the xpl from this archive (just overwrite the XPL in the plugin's mac_x64 folder): http://folko.solhost.org/avitab/AviTab-0.2.3-mac.xpl.zip

Does that fix the issue?

**Comment by ahmadworks** [comment]
Works perfect, thanks for you awesome work :D

**Comment by fpw** [comment]
Thanks for the confirmation that the fix works!
