### ISSUE TITLE
Add custom apps into avitab

### ISSUE THREAD

**Issue by zodiac1214** [fpw/avitab#112]
Hi,

Since we are talking about a tablet....is there a way to add custom apps into avitab? For example, can I write an app that connects to my VA so i can check  a few "company stuff" in the flight with the tablet?

**Comment by fpw** [comment]
Hi,

not yet, but this is on the long-term feature list. Here's a thread that explains my ideas for the future:

https://forums.x-plane.org/index.php?/forums/topic/180270-vision-for-the-future-of-avitab/
