### ISSUE TITLE
Thread X-Plane report

### ISSUE THREAD

**Issue by Pilotwillem** [fpw/avitab#114]
Maybe you can improve this version. all stuff test version do i somethimg wrong?

Model: iMac18,3, BootROM 447.80.3.0.0, 4 processors, Quad-Core Intel Core i7, 4,2 GHz, 64 GB, SMC 2.41f2
Graphics: Radeon Pro 580, Radeon Pro 580, PCIe, 8 GB
Display: iMac, Retina 5K (5120 x 2880), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 16 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x313641544632473634485A2D3247334532202020
Memory Module: BANK 0/DIMM1, 16 GB, DDR4 SO-DIMM, 2400 MHz, 0x859B, 0x435431364734533234414D2E4D31364642000
Memory Module: BANK 1/DIMM0, 16 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x313641544632473634485A2D3247334532202020
Memory Module: BANK 1/DIMM1, 16 GB, DDR4 SO-DIMM, 2400 MHz, 0x859B, 0x435431364734533234414D2E4D31364642000
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x16F), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.3)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD ST2000DM001, 2 TB
USB Device: Portable SSD T5
USB Device: USB30Bus
USB Device: Backup+ Hub
USB Device: Backup+ Hub BK
USB Device: MacBook Air SuperDrive
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Backup+ Hub
USB Device: USB 2.0 Hub
USB Device: Saitek X52 Flight Control System
USB Device: USB 2.0 Hub
USB Device: Saitek Pro Flight Rudder Pedals
Thunderbolt Bus: iMac, Apple Inc., 41.5

..................................... report
Thread 0:: Main Thread Dispatch queue: com.apple.main-thread
0   AviTab.xpl                    	        0x90ce2afa std::__1::shared_ptr<avitab::XPlaneEnvironment>::~shared_ptr() + 90
1   AviTab.xpl                    	        0x90ce1185 std::__1::shared_ptr<avitab::XPlaneEnvironment>::~shared_ptr() + 21
2   AviTab.xpl                    	        0x90dd93fb std::__1::__vector_base<std::__1::shared_ptr<maps::OverlayedNode>, std::__1::allocator<std::__1::shared_ptr<maps::OverlayedNode> > >::~__vector_base() + 283
3   AviTab.xpl                    	        0x90dd92d5 std::__1::vector<std::__1::shared_ptr<maps::OverlayedNode>, std::__1::allocator<std::__1::shared_ptr<maps::OverlayedNode> > >::~vector() + 21
4   AviTab.xpl                    	        0x90dd7985 std::__1::vector<std::__1::shared_ptr<maps::OverlayedNode>, std::__1::allocator<std::__1::shared_ptr<maps::OverlayedNode> > >::~vector() + 21
5   AviTab.xpl                    	        0x91471649 std::__1::pair<std::__1::pair<int, int> const, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >::~pair() + 25
6   AviTab.xpl                    	        0x91471625 std::__1::pair<std::__1::pair<int, int> const, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >::~pair() + 21
7   AviTab.xpl                    	        0x914715b1 std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 241
8   AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
9   AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
10  AviTab.xpl                    	        0x91471528 std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 104
11  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
12  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
13  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
14  AviTab.xpl                    	        0x91471528 std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 104
15  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
16  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
17  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
18  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
19  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
20  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
21  AviTab.xpl                    	        0x9147150e std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, void*>*) + 78
22  AviTab.xpl                    	        0x914714af std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::~__tree() + 79
23  AviTab.xpl                    	        0x91471455 std::__1::__tree<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::__map_value_compare<std::__1::pair<int, int>, std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > >, std::__1::less<std::__1::pair<int, int> >, true>, std::__1::allocator<std::__1::__value_type<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::~__tree() + 21
24  AviTab.xpl                    	        0x91471435 std::__1::map<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > >, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::~map() + 21
25  AviTab.xpl                    	        0x91471395 std::__1::map<std::__1::pair<int, int>, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > >, std::__1::less<std::__1::pair<int, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<int, int> const, std::__1::vector<std::__1::shared_ptr<xdata::NavNode>, std::__1::allocator<std::__1::shared_ptr<xdata::NavNode> > > > > >::~map() + 21
26  AviTab.xpl                    	        0x91471333 xdata::World::~World() + 35
27  AviTab.xpl                    	        0x91471305 xdata::World::~World() + 21
28  AviTab.xpl                    	        0x91471239 std::__1::__shared_ptr_emplace<xdata::World, std::__1::allocator<xdata::World> >::__on_zero_shared() + 41
29  AviTab.xpl                    	        0x90ce2b21 std::__1::shared_ptr<avitab::XPlaneEnvironment>::~shared_ptr() + 129
30  AviTab.xpl                    	        0x90ce1185 std::__1::shared_ptr<avitab::XPlaneEnvironment>::~shared_ptr() + 21
31  AviTab.xpl                    	        0x90dde278 std::__1::__assoc_state<std::__1::shared_ptr<xdata::World> >::__on_zero_shared() + 56
32  AviTab.xpl                    	        0x90e29f7a std::__1::__async_assoc_state<std::__1::shared_ptr<xdata::World>, std::__1::__async_func<std::__1::shared_ptr<xdata::World> (avitab::Environment::*)(), avitab::Environment*> >::__on_zero_shared() + 42
33  AviTab.xpl                    	        0x90cf5ef3 std::__1::future<double>::~future() + 115
34  AviTab.xpl                    	        0x90cea3e5 std::__1::future<double>::~future() + 21
35  AviTab.xpl                    	        0x90ce6e75 avitab::Environment::~Environment() + 69
36  AviTab.xpl                    	        0x90ceb3a9 avitab::XPlaneEnvironment::~XPlaneEnvironment() + 1033
37  AviTab.xpl                    	        0x90ceb515 avitab::XPlaneEnvironment::~XPlaneEnvironment() + 21
38  AviTab.xpl                    	        0x90ce349d std::__1::__shared_ptr_emplace<avitab::XPlaneEnvironment, std::__1::allocator<avitab::XPlaneEnvironment> >::__on_zero_shared() + 45
39  AviTab.xpl                    	        0x90ce2b21 std::__1::shared_ptr<avitab::XPlaneEnvironment>::~shared_ptr() + 129
40  AviTab.xpl                    	        0x90ce1185 std::__1::shared_ptr<avitab::XPlaneEnvironment>::~shared_ptr() + 21
41  AviTab.xpl                    	        0x90ce29e0 XPluginStop + 1024
42  XPLM                          	        0x897e84a3 UnloadOnePlugin(int) + 271
43  XPLM                          	        0x897e833c XPLMUnloadPlugins() + 53
44  X-Plane                       	       0x1099c937b XPPShutdownPlugins() + 59
45  X-Plane                       	       0x10974f6e8 MACIBM_finishup(int) + 360
46  X-Plane                       	       0x109608573 main + 83
47  dyld                          	       0x11cf474fe start + 462

**Comment by fpw** [comment]
Thanks for the report, should be fixed in the next release (0.4.9)
