### ISSUE TITLE
build make {avitab-plugin,Avitab-standalone} una to find uuid/uuid.h

### ISSUE THREAD

**Issue by jtison** [fpw/avitab#115]
My build of either target fails thusly:

[ 89%] Building CXX object CMakeFiles/avitab_common.dir/src/platform/Platform.cpp.o
/home/jtison/gitHub/avitab/src/platform/Platform.cpp:24:13: fatal error: uuid/uuid.h: No such file or directory
   24 | #   include <uuid/uuid.h>
      |             ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/avitab_common.dir/build.make:916: CMakeFiles/avitab_common.dir/src/platform/Platform.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:232: CMakeFiles/avitab_common.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/avitab_plugin.dir/rule] Error 2
make: *** [Makefile:124: avitab_plugin] Error 2

I'm running Fedora 34, I have a /usr/include/linux/uuid.h from the distro, and that's about it. Should I have another uuid.h? If not, shall I copy /usr/include/linux/uuid.h somewhere into the build tree and re-make? Or have you another suggestion?

Sorry for the ignorant question, I haven't done CXX makefiles in about 5 years, it's just now all coming back to me. I'm calling this a bug, but it's probably me.

Thanks.

**Comment by fpw** [comment]
Hi,

never tried compilation on Fedora - according to this thread:
https://superuser.com/questions/1175935/how-can-i-fix-uuid-uuid-h-no-such-file-error-in-centos

it might help to install `libuuid` and `libuuid-devel`
