### ISSUE TITLE
XP 12 

### ISSUE THREAD

**Issue by gitgwa** [fpw/avitab#128]
- Valid Navigraph Account linked
- No Airports displayed
- 17:45:37 i: AviTab logger initialized
17:45:37 i: Settings file: C:\X-Plane 12/Output/preferences/avitab.prf
17:45:43 v: Initializing X-Plane GUI driver
17:45:43 v: Initializing GUI driver
17:45:43 v: Discovering user sceneries...
17:45:43 v: LVGL thread has id 2
17:45:43 i: Loading nav data...
17:45:43 v: Loading airports...
17:45:43 i: Loading custom scenery airport for C:\X-Plane 12/Custom Scenery/X-Plane Landmarks - Dubai//Earth nav data/apt.dat
17:45:43 i: Loading custom scenery airport for C:\X-Plane 12/Custom Scenery/X-Plane Landmarks - Las Vegas//Earth nav data/apt.dat
17:45:43 i: Loading custom scenery airport for C:\X-Plane 12/Custom Scenery/X-Plane Landmarks - Saint Louis//Earth nav data/apt.dat
17:45:43 v: Loading default apt.dat
17:45:43 e: Couldn't load nav data: Couldn't open file: C:\X-Plane 12/Resources/default scenery/default apt dat/Earth nav data/apt.dat
17:45:43 v: Starting AviTab 0.4.6
17:45:43 i: No panel config - window only mode
17:45:43 v: Creating timer in thread 2
17:45:43 v: Creating timer in thread 2
17:45:43 v: Creating timer in thread 2
17:45:43 v: Creating timer in thread 2
17:45:43 v: TileCache spawned thread 5
17:45:43 e: Couldn't load nav data: std::exception
17:46:27 i: Closing tablet
17:46:27 i: No panel config - window only mode
17:46:57 v: Caching data ref sim/operation/misc/frame_rate_period
17:47:10 i: Showing tablet
17:47:21 v: Starting auth server
17:47:21 i: Navigraph login link: https://identity.api.navigraph.com/connect/authorize?-------------------
17:47:36 v: Accepting auth client
17:47:36 v: Checking phase 1 tokens
17:47:36 v: State: Check
17:47:36 v: RSA-SHA256 signature: Check
17:47:36 v: Nonce: Check
17:47:36 v: POST 'https://identity.api.navigraph.com/connect/token'
17:47:37 v: Checking phase 2 token
17:47:37 v: RSA-SHA256 signature: Check
17:47:37 v: Shutdown auth server
17:47:37 v: GET 'https://subscriptions.api.navigraph.com/1/subscriptions/valid'
17:47:38 v: HTTP request: Done, 264 bytes
17:47:38 v: GET_REDIRECT 'https://charts.api.navigraph.com/1/airports'
17:47:39 v: HEAD 'https://airport.charts.api.navigraph.com/idx/2236.0.0.0.json'
17:47:39 v: GET 'https://charts.api.navigraph.com/1/airports'
17:47:41 v: HTTP request: Done, 5934666 bytes
17:47:41 v: GET 'https://charts.api.navigraph.com/1/cycles/current'
17:47:42 v: HTTP request: Done, 112 bytes
17:47:42 v: GET 'https://charts.api.navigraph.com/1/signed_cookies'
17:47:43 v: HTTP request: Done, 638 bytes
17:48:15 i: Showing tablet
17:48:36 v: Want key input: 1
17:49:10 v: Want key input: 0
18:01:00 v: Want key input: 1
![Screenshot 2022-09-10 180429](https://user-images.githubusercontent.com/10481975/189507314-dad1ee6f-1875-44c3-854d-f095fd40f996.jpg)

**Comment by fpw** [comment]
You are using AviTab 0.4.6 - the first version compatible with XP12 is 0.5.1
