### ISSUE TITLE
mupdf breaking changes

### ISSUE THREAD

**Issue by kbrandwijk** [fpw/avitab#13]
I was following your 'compiling' instructions on the wiki, but because mupdf did some breaking changes in their latest version (1.14.0rc1), I ran into all kinds of errors. Manually downloading the 1.13.0. version and compiling that one fixed those.

**Comment by fpw** [comment]
Thanks for the report, I'll consider the mupdf update in one of the next versions.

**Comment by kbrandwijk** [comment]
I also get build errors on 1.13.0 (when building mupdf). I know it's not your fault, but maybe you ran into that?

```
CC build/release/platform/gl/gl-main.o
platform/gl/gl-main.c:1677:2: warning: implicit declaration of function
      'glutSetOption' is invalid in C99 [-Wimplicit-function-declaration]
        glutSetOption(GLUT_ACTION_ON_WINDOW_CLOSE, GLUT_ACTION_GLUTMAINL...
        ^
platform/gl/gl-main.c:1677:16: error: use of undeclared identifier
      'GLUT_ACTION_ON_WINDOW_CLOSE'
        glutSetOption(GLUT_ACTION_ON_WINDOW_CLOSE, GLUT_ACTION_GLUTMAINL...
                      ^
platform/gl/gl-main.c:1677:45: error: use of undeclared identifier
      'GLUT_ACTION_GLUTMAINLOOP_RETURNS'
        glutSetOption(GLUT_ACTION_ON_WINDOW_CLOSE, GLUT_ACTION_GLUTMAINL...
```

**Comment by kbrandwijk** [comment]
In the meantime, maybe you could at least update the wiki to reflect this.

**Comment by fpw** [comment]
These errors indicate that you're compiling with X support. Try passing HAVE_X11=no and HAVE_GLUT=no to mupdf's configure parameters.

**Comment by kbrandwijk** [comment]
Great, thanks for your help! Worked like a charm. Searching for HAVE_GLUT actually brought up those instructions :)  The only other thing is that I had to turn off -Werror, because of a number of `[-Wunused-lambda-capture]` warnings, but now it builds like a charm. I can finally start testing now.

**Comment by fpw** [comment]
Good luck! I hope it's not too hard to dig into the undocumented code. Feel free to ask any questions about the architecture etc. 
I updated the Wiki to mention the supported mupdf version.

**Comment by kbrandwijk** [comment]
Hmmmm... only one error left:
```
[100%] Linking CXX shared library AviTab.xpl
ld: framework not found XPLM
```
I did update CMakeLists.txt to add `link_directories("/opt/XSDK/Libraries/Mac")` because I'm on Mac, but that didn't help...

Any suggestions?

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/46258603-e8ed3680-c4cd-11e8-9526-ff9e3417ad81.png)

It runs! Thanks for your assistance! Now on to the source code 🎉

**Comment by fpw** [comment]
* Increased required mupdf version to 1.14.0
* Added framework search path for OS X CMake
* Fixed lambda warnings so -Wall works on newer OS X compilers
