### ISSUE TITLE
A way to read the METAR?

### ISSUE THREAD

**Issue by crazytimtimtim** [fpw/avitab#136]
Hi, developer here. Is there a way I can read the METAR from Avitab from a dataref?

**Comment by crazytimtimtim** [comment]
?

**Comment by crazytimtimtim** [comment]
What I mean is more of something like this:
- Set a dataref for an airport to search for
- Call a command to search for it
- Return the METAR result in another dataref

**Comment by fpw** [comment]
Hi,

as a developer, it's probably easier to implement this yourself. X-Plane 12 includes a new SDK function that does exactly this - see the new XPLMWeather.h file.
For X-Plane 11, AviTab simply reads the METAR.rwx file in X-Plane's root directory.

**Comment by crazytimtimtim** [comment]
Thanks!
