### ISSUE TITLE
Feature request: Navigraph VFR enroute moving map

### ISSUE THREAD

**Issue by jonaseberle** [fpw/avitab#139]
Thank you for this amazing software!

We already enjoy the Navigraph upper and lower IFR enroute maps.

Is it possible to add the VFR enroute map, too? They have been [introduced with Navigraph Charts 8](https://navigraph.com/blog/charts-8-release). They include VFR reporting points, routes and patterns for many airports and it would be great to have that in the plane.
Since I am on Linux with X-Plane I can't use their moving map feature thus I am hoping even more that Avitab could include it.

Just like the IFR enroute maps they are also available in the Navigraph charts app / web app and they look technologically similar (they use Slippy maps, .pbf, in their [charts web app](https://charts.navigraph.com/)).

**Comment by fpw** [comment]
Thanks for making me aware, implemented in https://github.com/fpw/avitab/commit/aec896d41f43d9aa094a2c28321448d1c008d66a and will go into the next release.

**Comment by jonaseberle** [comment]
Fantastic, thank you so much!
