### ISSUE TITLE
Working on additional features

### ISSUE THREAD

**Issue by kbrandwijk** [fpw/avitab#14]
I love avitab, and I want to add some features to it:

- GPS on/off to have a static map without showing your position (for more realistic VFR flying)
- PilotEdge connect button (for easy connect/disconnect)
- Show traffic on moving map (more specifically PE traffic)
- Weight/balance editing

I'm doing these in a fork, and I will create a PR when it's done, just wanted to let you know in case you happen to be considering any of these features.

**Comment by fpw** [comment]
Thanks for trying to contribute! I'll happily integrate the first feature you mentioned into the master. I'm not sure if the other three features fit into AviTab's philosophy: For reasons of realism, I want AviTab to be somewhat like a real tablet with GPS and Internet access - but no connection to the aircraft. Showing traffic or editing the weight breaks with this philosophy I think. Right now there is no way to even modify a dataref, so you'd have to lay some foundations deeper in AviTab's systems, mainly the environment classes.

If you make the other three features optional (e.g. a setting in the JSON config), I'll integrate them as well.

**Comment by kbrandwijk** [comment]
I agree these apps should be modelled in such a way that one could easily enable/disable them indeed, or even have them be their own library, that you could add to the plugin folder and avitab would load them.

Regarding option 3: Most tablets apps nowadays (ForeFlight etc.) have the possibility to use a ADS-B enabled GPS device and actually show traffic, so I think that one doesn't break the philosophy.

**Comment by kbrandwijk** [comment]
You can add an XChecklist integration to that list as well, would really like them on the tablet 😄
