### ISSUE TITLE
Add description of charts from ChartFox

### ISSUE THREAD

**Issue by cyberang3l** [fpw/avitab#141]
When finding Chartfox charts for an airport through AviTab, the listed documents only show the corresponding document codename. In the screenshot below, you can see the docs listed with names suchs as `CF-5-1: ENAN 5 - 1`, `CF-5-2: ENAN 5 - 2` etc:
![image](https://user-images.githubusercontent.com/5658474/232337573-0f1fc2fb-2968-40c9-a910-6aaa2c590b5a.png)

It seems like ChartFox provides human friendly titles as you can see for the same airport in the next screenshot:
![image](https://user-images.githubusercontent.com/5658474/232337805-47508fd9-eb41-4766-a239-d48a538cadf0.png)

In this example, the title for the document `CF-5-1: ENAN 5 - 1` is `RNP RWY 14` and doc `CF-5-2: ENAN 5 - 2` is `RNP RWY 14 Recommended coding`.

It would be nice to show this additional title in AviTab to make finding the correct document easier and faster, without having to click through potentially 10s of docs before finding the one you're looking for. For instance, something like this:

```
ENAN 5 - 1: RNP RWY 14
ENAN 5 - 2: RNP RWY 14 Recommended coding
...
```

**Comment by fpw** [comment]
Thanks for the suggestion, will make it into the next version.
![grafik](https://user-images.githubusercontent.com/5798899/233793626-1fefb330-1ed7-4cac-aa5e-a4294ad4c912.png)
