### ISSUE TITLE
Error linking Navigraph

### ISSUE THREAD

**Issue by Honu4** [fpw/avitab#142]
I'm getting a "AviTab Error: Invalid RS256 signature" when trying to link my Navigraph to Avitab. This is just after update to v0.6.1. Previous version linked fine.

**Comment by fpw** [comment]
Interesting, never had a report of this error before. Sorry about that.

Can you please try deleting the Navigraph directory in X-Plane/resources/plugin/AviTab and try again?

**Comment by Honu4** [comment]
Okay, more info. MacOS v12.6.5, X-Plane v12.04r3. Deleted folder as instructed. No difference. Same error. Deleted entire AviTab plugin folder and reinstalled. Same error. Do I need to update to latest Beta version of X-Plane?

**Comment by fpw** [comment]
Thanks for the test. This is not related to X-Plane, it must either be on AviTab's or Navigraph's side I think. 
Are you running on an M1 or Intel Mac? If M1, with or without Rosetta? Could you maybe attach both X-Plane's and AviTab's log? The latter is in AviTab's plugin directory.

**Comment by Honu4** [comment]
M1, with Rosetta
[AviTab.log](https://github.com/fpw/avitab/files/11302339/AviTab.log)

**Comment by Honu4** [comment]
[Log.txt](https://github.com/fpw/avitab/files/11302343/Log.txt)

**Comment by fpw** [comment]
Thanks for the log. One last questions before I try to reproduce this, which browser are you using? And are there any browser extensions? One thing I notice in the logs is that your browser connects to AviTab twice after you click Allow in Navigraph, which is very unusual.

**Comment by Honu4** [comment]
Chrome, Version 112.0.5615.137 (Official Build) (arm64)

**Comment by fpw** [comment]
Thanks, I can reproduce it when using M1 + Rosetta. Will get back to you when resolved.

**Comment by fpw** [comment]
Please redownload the release and try again, does this fix it?

**Comment by Honu4** [comment]
"AviTab: Success, you can close this tab now!"

Thanks! All good.

**Comment by fpw** [comment]
Thanks for the feedback and sorry again!
