### ISSUE TITLE
XPLM Error XP 1155r2 in Avitab 0.6.1

### ISSUE THREAD

**Issue by hkodonas** [fpw/avitab#147]
Under "weather" section the  "XPLM Error" irrespective of the station that is chosen.
![image](https://user-images.githubusercontent.com/132197841/235347138-befd0787-2727-4391-9ca5-86c2d4167afd.png)

**Comment by fpw** [comment]
Thanks for the report, could you please attach X-Plane's log file and the XPLM_64.dll file from X-Plane/Resources/plugins?

**Comment by hkodonas** [comment]
[Log.txt](https://github.com/fpw/avitab/files/11361917/Log.txt)
Attached is the log.txt. Unfortunately I am not allowed to upload the XPLM_64.dll file.

**Comment by fpw** [comment]
Could you please try the attached version by replacing the XPL file in plugins/AviTab/win_x64 with the version inside the attached ZIP?
[AviTab.zip](https://github.com/fpw/avitab/files/11415090/AviTab.zip)

**Comment by hkodonas** [comment]
Hello,
I have replaced the dll file with the new that you have attached and seems that the issue has been resolved now.
Thanks for help and quick response.
Best Regards,
Harry

**Comment by fpw** [comment]
Thanks for the feedback, this is fixed in 0.6.2 then.
