### ISSUE TITLE
Chartfox charts not woking 

### ISSUE THREAD

**Issue by raed23c** [fpw/avitab#151]
For some reason even after I enable chartfox on avitab no charts show up. This is on the ZIBO 738.
![image](https://github.com/fpw/avitab/assets/64880675/3e54f6e5-b207-4d08-b8d9-2527ff8b6854)
![image](https://github.com/fpw/avitab/assets/64880675/1a8fa7f3-ab36-4e9c-9a4e-b7b227bf4776)
Can anyone help me fix this? I tried reinstalling avitab but that didnt help.

**Comment by Noobetski** [comment]
same thing on toliss a320neo

**Comment by Noobetski** [comment]
I think it's because some airport charts are not passed for some reason. Airports that are confirmed to not work: UWUU, UNKL, UEEE

**Comment by fpw** [comment]
Chatfox has a new API and AviTab hasn't been updated to use that yet. We're on it, and after the migration it should work again.
