### ISSUE TITLE
Issue in navigraph linking to xplane 12 - weather information not showing

### ISSUE THREAD

**Issue by drkarem** [fpw/avitab#157]
charts are not linked even though I pay every month, weather information is not showing on AVITAB plus approach and departure maps all show "0". 
When the desktop app of Navigraph charts opens it shows all this data fine, the issue is the link to XPLANE 12

**Comment by fpw** [comment]
Please try deleting the "Navigraph" directory inside AviTab's plugin directory and then link your account again. Does that help? Please reopen if not.
