### ISSUE TITLE
Aircraft Manuals app always starts in X-Plane root folder

### ISSUE THREAD

**Issue by telephono** [fpw/avitab#158]
When I try to start the Aircraft Manuals app in AviTab, I always get the following message:
"It is recommended to put your aircraft's manuals into a dedicated folder inside your aircraft folder. Avitab looks for folders: 'manuals' 'docs' 'handbook'."

After that AviTab allways shows the X-Plane 12 root folder.

![Screenshot](https://github.com/fpw/avitab/assets/111712/49d6f13a-7a90-4566-9552-466cc7b12505)

I tried this in different aircraft, all containing a "manuals" folder with .pdf or .jpg files inside.

The paths would be as follows:
`X:\X-Plane 12\Aircraft\Felis\B742\manuals`
`X:\X-Plane 12\Aircraft\Shenshee\Boeing_720B\manuals`
`X:\X-Plane 12\Aircraft\X-Aviation\IXEG 737 Classic Plus\manuals`

I'm running X-Plane 12.07r1 and AviTab 0.6.3.

**Comment by mjh65** [comment]
This is fixed in a recent PR, and will be resolved in the next Avitab release.
