### ISSUE TITLE
X-Plane 12 freezes when quitting through the menu (Event Viewer points to AviTab)

### ISSUE THREAD

**Issue by argo0n** [fpw/avitab#160]
Title.

This happens 100% of the time I quit X-Plane 12 through the menu. It also happens if I simply open and quit X-Plane 12 without starting a flight.

I'm on X-Plane 12.07r1, AviTab 0.6.3. I've tried a thorough reinstall of the AviTab plugin to no avail.

![image](https://github.com/fpw/avitab/assets/67531837/2a613743-5d32-4928-bcc1-b3e40235dfa5)

[Attached is my AviTab.log](https://github.com/fpw/avitab/files/13197134/AviTab.log). There is no crash report available.

**Comment by fpw** [comment]
Hello,

are you by chance using Reshade? If yes, does the problem disappear if you disable Reshade?
