### ISSUE TITLE
Deprecated Datarefs XP12.08b3

### ISSUE THREAD

**Issue by CalibraNR** [fpw/avitab#185]
0:17:30.684 E/PLG: The plugin AviTab called the SDK function XPDisplayDismissableAlert from outside of a drawing callback. This is illegal! This plugin needs to be fixed.

This prompts a warning message inside XP12.
[AviTab]: Dataref 'sim/cockpit/switches/anti_ice_on' is deprecated and will be removed in a future version.

Those are only listed inside Log.txt (They had not prompted any warnings inside sim).
[AviTab]: Dataref 'sim/cockpit2/controls/flap_ratio' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/barometer_sealevel_inhg' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/temperature_ambient_c' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/visibility_reported_m' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/wind_direction_degt' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/wind_speed_kt' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/wind_now_z_msc' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/wind_now_x_msc' has been replaced. Please use the new name.
[AviTab]: Dataref 'sim/weather/runway_friction' has been replaced. Please use the new name.

**Comment by fpw** [comment]
Thanks for the report. That's pretty interesting because AviTab doesn't use any of these datarefs. It uses X-Plane's `XPLMGetMETARForAirport` function to retrieve the weather, so I can only imagine that this functions uses deprecated APIs internally, and since it's called from AviTab, X-Plane basically complains about itself while blaming AviTab.

If you still have the full log, could you please submit this bug report to LR and simply include this message?

**Comment by fpw** [comment]
I contacted LR and `XPLMGetMETARForAirport` doesn't use datarefs. Also, AviTab doesn't use `XPDisplayDismissableAlert`. I believe this is a bug in another plugin that X-Plane falsely related to AviTab.

**Comment by CalibraNR** [comment]
Hi! I tried several times to replicate this issue with no luck. Unfortunately I did not saved the related log.txt. in any case, thank you for your attention and time invested to share your knowledge with the community. Cheers
