### ISSUE TITLE
Implement new ChartFox  API

### ISSUE THREAD

**Issue by fpw** [fpw/avitab#196]
The old API is deprecated and will be removed soon, so AviTab needs to migrate.

**Comment by timdah** [comment]
Hey! What is the current status of this? If it's desired, I am willing to contribute here.

Am I right in assuming that this is related to the error metioned there? https://forums.x-plane.org/index.php?/forums/topic/299136-chartfox-loading-fails-with-error/

**Comment by mjh65** [comment]
Yes, I am almost finished updating the Chartfox integration to use Chartfox's v2 API. I will submit a PR shortly, and comment here when it is ready.

**Comment by timdah** [comment]
Awesome, thanks for your work 👍
