### ISSUE TITLE
Avitab 0.3.11 - false airport metar

### ISSUE THREAD

**Issue by vinKaiZen** [fpw/avitab#27]
Hello,

i just noticed that if you will choose an airport,
the recceived & shown meta is from an different IVAO aiport. 

Bug? I tried clean installation and restarts with same mismatching result.

**Comment by fpw** [comment]
Hi,
how do you know that this is a different METAR? AviTab displays X-Plane's internal METAR information, so if you use a weather addon, the information might not be reflected back to X-Plane and AviTab can't know the weather you're using. See the last FAQ entry:  https://forums.x-plane.org/index.php?/forums/topic/155646-avitab-frequently-asked-questions/

**Comment by fpw** [comment]
Could you please attach the METAR.rwx file in X-Plane's root directory? If I remember correctly, the NOAA plugin writes the METAR information in the format of X-Plane 10. The new format expects two lines per airport, e.g.:

```
2018/08/10 17:50
EDDF 101750Z 22009KT CAVOK 23/06 Q1021 NOSIG
```

Even if you disable the plugin, its last output file will probably still be there. There's a patch for the plugin here: https://forums.x-plane.org/index.php?/forums/topic/155662-correction-to-show-metar-on-avitab-for-noaa-weather-users/

Maybe that solves the issue.

**Comment by vinKaiZen** [comment]
I´ve done this before. The problem is still present before and after the file changement.
It´s not the written problem that no weather is shown, but only the metar and IVAO from a complete different location. The last letter of ICAO + next letter.

Tried with complete blank simulator and still the same result. I will post pictures later when i´m at home

**Comment by fpw** [comment]
Thanks. Please also include the METAR file so I can analyze the cause.

**Comment by vinKaiZen** [comment]
Strange things happens… , i´ve done 5 xplane restarts, after 2nd time the shown ICAO Airport directly above the metar line was away, but the weather nearly matches with noaa weather. Only metar and 1 hour behind (metar file was fine). after 3 further restarts it matches to metar file.. strange… i will keep an eye on that. Actual there is no problem

**Comment by vinKaiZen** [comment]
No issue since now.
