### ISSUE TITLE
Guide for implementing Avitab in an aircraft

### ISSUE THREAD

**Issue by connorwyatt** [fpw/avitab#29]
Hi, I'm loving using Avitab, but particularly when it is integrated into an aircraft. For example the Zibo mod 737 feels much nice to use than a floating window in the sim, as it feels more immersive.

Is there a guide for integrating it into an aircraft model? At the moment I have no idea how the Avitab gets placed in the Zibo 3D model and would be interested in know how to get started.

Can you point me in the right direction?

Thanks, and great work on the project!

**Comment by fpw** [comment]
Hi @connorwyatt,
the 3D integration was contributed by nhadrian from the X-Plane.org forum, so unfortunately I don't know much about it myself. However, Ekre wrote a short tutorial here: https://forums.x-plane.org/index.php?/forums/topic/155643-aircraft-with-avitab-integration/&do=findComment&comment=1494989

**Comment by connorwyatt** [comment]
Hi @fpw thanks for the information, I will take a look at the link you provided.

Thanks again for the awesome plugin!
