### ISSUE TITLE
Feature Request: Checklists

### ISSUE THREAD

**Issue by chrismbeckett** [fpw/avitab#35]
Any plans to port a checklist feature like the one in the 737 Ultimate to a generic feature in AviTab? Is anyone working on this? If not, would you welcome some development help or a pull request to add this feature?

**Comment by fpw** [comment]
Hi, sorry for the late reply. Please see here, this will allow others to implement general checklists: https://forums.x-plane.org/index.php?/forums/topic/180270-vision-for-the-future-of-avitab/

**Comment by chrismbeckett** [comment]
This is an outstanding idea. I think that a lot of existing plugins with custom UI would benefit greatly from just integrating into AviTab. It will really make AviTab to central interface to plugin capabilities. I would certainly chip in and build many plugins for AviTab once this API is available. Thanks, I will add my comments to the forum topic.
