### ISSUE TITLE
Question: Save settings

### ISSUE THREAD

**Issue by Anduin2017** [fpw/avitab#38]
When I change some basic settings in Avitab, it works fine. But when I reboot the x-plane program, all settings in Avitab was reset to default.

So every time before the flight I have to spend a lot of time to change settings in Avitab to my preferred settings. Is there any solution for me to save my Avitab settings and load it during initialization?

Thanks!

**Comment by fpw** [comment]
Hi, can you give an example for a setting that you would like to save?

**Comment by Anduin2017** [comment]
I need to change:

Configure and customize -> General Config -> Global Units -> KGS.
Configure and customize -> Hardware -> Nosewheel axis -> YAW.
Configure and customize -> Visual Effects -> SHOW FPS -> ON.

Every time I start the simulator I need to change those settings. Really wish that it can be saved!

Thanks so much for your quick response!

**Comment by fpw** [comment]
Thanks for the clarification. None of these settings are actually related to AviTab.

You are using the Zibo 737, it displays its own EFB and AviTab in the same tablet. This confuses a lot of people into thinking that the whole EFB *is* AviTab. But AviTab only implements the part of Zibo's EFB that's visible if you click on the "AviTab" icon in his EFB, i.e. the map app, the charts app etc.

The settings you mentioned are part of Zibo's EFB and I am in no way related to that project. Please forward your request to his project.
