### ISSUE TITLE
Resolution too low

### ISSUE THREAD

**Issue by Chryseus** [fpw/avitab#4]
Many charts, particularly those of larger airports are nearly impossible to read without using a lot of zoom, I attached an example chart that is hard to read.

[EG_AD_2_EGKK_2-1_en_2017-10-12.pdf](https://github.com/fpw/avitab/files/1869845/EG_AD_2_EGKK_2-1_en_2017-10-12.pdf)

**Comment by fpw** [comment]
The next beta should hopefully fix the bug that dragging doesn't work in VR. Do you think it'd enough if you could use easy panning gestures using the controllers to move the chart without the buttons? Increasing the resolution would also require a larger window.

**Comment by Chryseus** [comment]
Panning would certainly help a lot.
One possible solution I can think of would be rendering the entire page at a higher zoom level then stitching and scaling the result, although I'm not entirely sure how viable this would be and what kind of performance impact it would have.

**Comment by fpw** [comment]
The latest release (0.0.5) supports panning now when using the latest X-Plane beta (4). Is it more usable for you now?

**Comment by fpw** [comment]
As the latest version supports resizing of the window, zooming and panning, I'm now closing this issue.
