### ISSUE TITLE
jeppesen chart (no navigraph)

### ISSUE THREAD

**Issue by cherrymx89** [fpw/avitab#46]
hello good, could you add Jeppesen chart not the navigraph, I can't check them in the avitab,
please.
![Sin título](https://user-images.githubusercontent.com/58763366/72101091-8b0ee780-32e9-11ea-8059-329415f545ae.png)

**Comment by fpw** [comment]
Can JeppView export the charts in any common format?

**Comment by Eureka0225** [comment]
> Can JeppView export the charts in any common format?

Yes, it can export to PDF

**Comment by fpw** [comment]
In that case, I would suggest to just import the PDF into AviTab. Since I don't have JeppView, I have no idea about their file formats etc.
