### ISSUE TITLE
VOR-DME-NDB overlay

### ISSUE THREAD

**Issue by erdebugger** [fpw/avitab#51]
Please, add a new overlay like airports. I think that a new VOR-DME-NDB overlay could help a lot.

**Comment by fpw** [comment]
David is already working on that 😄 

![NavaidOverlays](https://user-images.githubusercontent.com/5798899/79556519-7f2d8100-80a1-11ea-9335-161748744941.jpg)

**Comment by erdebugger** [comment]
Thanks. I like to know it!
If you need any help or tester, please contact with me.
I can write code quickly or look for any issue/bug.
Regards!
