### ISSUE TITLE
Betterpushback

### ISSUE THREAD

**Issue by Rdtcmttsa** [fpw/avitab#54]
Hello folks, i'm just wondering where do you put the file. you don't seem to be clear on that.
Or im just not in the right place.
THX...RobertC

**Comment by fpw** [comment]
Hi, this is AviTab. It's not related to BetterPushBack at all. Please see here for BetterPushBack: https://github.com/skiselkov/BetterPushbackC

**Comment by Rdtcmttsa** [comment]
Thank you, for that info.RobertC -- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 5/4/20, 6:53 PM Folke Will <notifications@github.com> wrote:

   
  Hi, this is AviTab. It's not related to BetterPushBack at all. Please see here for BetterPushBack: https://github.com/skiselkov/BetterPushbackC
