### ISSUE TITLE
Build under msys2/mingw64

### ISSUE THREAD

**Issue by gsal** [fpw/avitab#64]
I did see another long issue (now closed) with the same exact problem.
```
 > /c/Users/salazag/Downloads/glfw
cmake ../glfw-3.3.2
-- The C compiler identification is GNU 10.1.0
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17763 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Check for working C compiler: /mingw64/bin/cc.exe
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17763 to use this system, . . . 
```

These are a few values from the environment:
```
 > /c/Users/salazag/Downloads/glfw
env | grep MINGW
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
MINGW_CHOST=x86_64-w64-mingw32
MSYSTEM=MINGW64
MINGW_PREFIX=/mingw64
 > /c/Users/salazag/Downloads/glfw
uname -a
MINGW64_NT-10.0-17763 md2ysbtc 3.1.4-340.x86_64 2020-05-22 08:28 UTC x86_64 Msys
```

I wonder what value GLFW is expecting and how picky it may be...is there a way for me to overwrite `MINGW64_NT-10.0-17763` with just `MINGW64_NT-10.0` ?  or some trick along those lines?

**Comment by fpw** [comment]
Hi,

you don't need to download GLFW yourself, that's what MSYS2 is for!

From the other issue you opened, it looks like you might be using an incorrect shell. MSYS is a little strange at first, that's why I described the compilation here:

https://github.com/fpw/avitab/wiki/Compiling

Does that help?

**Comment by gsal** [comment]
Ha, ha!...my mistake. 

Thanks for your quick reply, though.  I googled my issue and found a thread here; thus, I created an issue here, too...without realizing that this project does not have much to do with GLFW...I thought I was right at the GLFW site.

But, you actually kind of solved my problem...I don't have to compile glfw, I can just install it with pacman.  Thank you for that.   Now, I just need to figure how to install glad.

**Comment by fpw** [comment]
What do you need glad for? If you install GLFW through Pacman, it will include all dependencies. And since it is dynamically linked, you should be fine.

**Comment by gsal** [comment]
Ah, ok, thanks.   

At this point I don't exactly know what I need or what for...I am just browsing around for some quick and easy way to create a minimal GUI and visualize some 2D plots and a 3D mesh...from Julia.

Of course, there is always GTK and also found GR; but, just yesterday I learned about Immediate Mode GUI...talk about rather minimal code to produce something...I just do not know any OpenGL, should I need to mix and match toolkits...we shall see.
