### ISSUE TITLE
Feature Request - List custom charts in the Airports app

### ISSUE THREAD

**Issue by oobayly** [fpw/avitab#66]
I've organised custom charts in the `charts` directory by the ICAO airport code, like so:
![image](https://user-images.githubusercontent.com/3430117/88524948-eab4b200-cff1-11ea-86c0-90da6c97fac9.png)

It would be useful if the Airport app could list any charts in a folder with the same ICAO code. This could be done in a similar way to how the Navigraph charts are listed - eg appending "Custom Charts" to the list, or if there is no link Navigraph account, just the charts on their own.

![image](https://user-images.githubusercontent.com/3430117/88526374-c9ed5c00-cff3-11ea-8f3e-7b2b7e0d0b0f.png)

I'm not a big C++ developer, especially when it comes to GUI stuff, but I'll have a stab at getting a PR together.

**Comment by Gfurst** [comment]
Was about to suggest the same thing, would be wonderful for those of us who don't use navigraph but can get the charts on our own.
