### ISSUE TITLE
How to manually calibrate a chart?

### ISSUE THREAD

**Issue by tiagomelo** [fpw/avitab#67]
Hi!

So, I have a symlink in such way that `Mercato` folder -> `charts` folder. So, under `maps -> `Mercator`, I'm able to see my charts.

Now I'm trying to manually calibrate it accordingly with the Wiki, but it's not working.

1) opened it, clicked in `track` button; since I don't have the correspondent `.json`, it will ask me to calibrate it
2) at this moment, a suggested lat/long appears - not sure to where it is pointing 
3) so I put the red box in a distant point in the chart (say, it's an movement airport chart) and then click in `track` button; it becomes blue
4) after that, I move the blue box to where my aircraft is standing, then erase the field and press `track` button again - it will get the current lat/long of the aircraft, and then press `track` button.
5) although it shows the red airplane icon pointing to where the aircraft is, it does not follows the aircraft movement in a right way.

I know that I could do it through Little Navmap, but I really wanted to map it to my charts, since I have access to Jeppesen but not to Navigraph.

What am I doing wrong?

**Comment by fpw** [comment]
Hi,

in step 3, you moved the red box to a distant point. Did you also put in the coordinates of that point before clicking the button? 

Basically, you need to select two distant points (both horizontal and vertical distance required), enter the coordinate of the first point first, click the button, enter the next point and click the button again, always moving the square to the point before clicking.

Does that help?

**Comment by tiagomelo** [comment]
Hi Folke, thanks so much for your replying!

What I've done was:

1) got the airport chart from Jeppesen
2) grabbed a lat/long position for a distant parking spot from where my aircraft is parked
3) put that lat/long into the input, moved the red box to its approximate position (the way I see in the chart)
4) then, it become blue - so moved it to where my aircraft is parked, cleaned input text, hit 'track' button to grab the aircraft lat/long position, and then the aircraft icon is displayed in map.

Then when I'm moving with the aircraft and take a taxiway, it seems to be right, but then it stops from mapping the aircraft movement upon a given point

**Comment by fpw** [comment]
Hm.. is it possible the map is not oriented with north = up? In that case, you would need to rotate it so that north is up in an external image program as AviTab only supports maps where north is exactly upwards.

**Comment by tiagomelo** [comment]
actually nope, the chart is oriented with north (up)

**Comment by fpw** [comment]
Could you please attach the map and the JSON file here? Maybe @dave6502 has an idea.

**Comment by dave6502** [comment]
Could you also attach the AviTab.log - from a run where you do the calibration. The Avitab.log file should have a couple of lines in it that show how the coordinates were parsed by Avitab.
