### ISSUE TITLE
Feature Request - Ability to change Avitab position on runtime

### ISSUE THREAD

**Issue by airfightergr** [fpw/avitab#68]
I am implementing Avitab on FF A350 OIS display, charts page. But the aircraft has the option to switch OIS display from left to pedestal. In that case avitab must be disabled not to be on top of other pages like FMC, checklists, etc.

It will be great to be able to follow OIS display position by changing Avitab position on runtime.

**Comment by fpw** [comment]
Here's a (Windows) XPL that supports this feature, please test and I'll include it in the next version.
The new datarefs are avitab/panel_left, avitab/panel_width, avitab/panel_bottom, avitab/panel_height.

[AviTab.zip](https://github.com/fpw/avitab/files/5288471/AviTab.zip)

**Comment by airfightergr** [comment]
Works perfectly! Thanks!

**Comment by fpw** [comment]
This will be released in AviTab 0.4.3.
