### ISSUE TITLE
AviTab 0.3.21 CTD Opening GeoTIFF Sectionals on Manjaro

### ISSUE THREAD

**Issue by Xarius86** [fpw/avitab#74]
AviTab 0.3.21
X-Plane 11.50r2 Vulkan and OpenGL
Manjaro Fully Updated 09/03/2020

AviTab is linked to my Navigraph account and will open charts from there just fine. I also have sectional GeoTIFF charts that I've downloaded from the FAA. Whenever I attempt to open GeoTIFF's it's an immediate CTD without any useful log information. The AviTab.log shows entries for opening the previous Navigraph chart, and then nothing. These exact charts worked just fine with the same setup under Ubuntu 20.04. So, I'm guessing there is some sort of library difference that is causing a problem but the logs are providing nothing for information. The X-Plane log provides no useful information either, it doesn't even register the crash.

**Comment by fpw** [comment]
Thanks for the report and sorry about the crash! Did X-Plane write a crash dump in Output/Crash Reports?

**Comment by Xarius86** [comment]
> Thanks for the report and sorry about the crash! Did X-Plane write a crash dump in Output/crash_reports?

Unfortunately not. That's why this particular error has me confused. Nothing is written in the X-Plane log, nothing is written in the AviTab log, and there isn't a crash dump. It's just a straight CTD. I'm not sure where else to look for information as to what is causing it.

**Comment by Xarius86** [comment]
The problem **_wasn't_** anything to do with AviTab specifically, or even library differences as I suspected. 

The defaults for memory and swap management are different between Ubuntu and Manjaro. After tweaking various memory/swap settings the issues no longer appear.
