### ISSUE TITLE
Feature Request: AI Traffic

### ISSUE THREAD

**Issue by jct32** [fpw/avitab#76]
Hello,

I do a lot of VFR flying and use AviTab for it. I was wondering if it would be possible to add in AI aircraft or even maybe network traffic (VATSIM) to the maps in AviTab so that I could see other traffic around me while in VFR.

**Comment by fpw** [comment]
Hi,

this was recently implemented and will make it into the next beta 🙂

**Comment by jct32** [comment]
Do you know when the next beta might be? Really looking forward to this feature since I can't get ForeFlight to work properly with traffic.

**Comment by fpw** [comment]
Hi,

you can find the latest beta here, it already includes the AI traffic option: https://forums.x-plane.org/index.php?/forums/topic/231113-new-avitab-beta-044-navigraph-enroute-charts/

**Comment by jct32** [comment]
Thank you very much! I'm going to load in now!
