### ISSUE TITLE
METAR

### ISSUE THREAD

**Issue by okanergknil** [fpw/avitab#77]
Can you please METAR service inside 🥇

**Comment by SpaceEnthusiast** [comment]
You can already get METER info at the bottom when you type in an airport

**Comment by okanergknil** [comment]
always say no weather information avaliable

4 Eki 2020 Paz 17:51 tarihinde SpaceEnthusiast <notifications@github.com>
şunu yazdı:

**Comment by SpaceEnthusiast** [comment]
Just click on the refresh button, usually works for me

**Comment by fpw** [comment]
This is fixed in the latest beta - you no longer need to click the refresh button there.
