### ISSUE TITLE
AviTab causing CTD when CSL get rendered

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [fpw/avitab#87]
Hi,

I just had CTDs with X-Plane 11.51 and AviTab 0.4.5. They always happened when I connected to VATSIM and my pilot client (swift) started to render aircraft in X-Plane. I went back to AviTab 0.3.21 and everything was fine again.

[CTD_dmp-files.zip](https://github.com/fpw/avitab/files/5876043/CTD_dmp-files.zip)

**Comment by fpw** [comment]
Hi, could you please try again with 0.4.6? There was a bug with 3rd party traffic causing a crash that's fixed in 0.4.6 - uploading here ASPAP.

**Comment by FlyingFoxVATSIM** [comment]
Haha, nice, I should have waited 2 minutes before creating the issue :)

I just tested 0.4.6 and it does work! Beautiful, good job!!
