### ISSUE TITLE
Unreliable map loading

### ISSUE THREAD

**Issue by Chryseus** [fpw/avitab#9]
Initially the default zoom level of the map loads fine but other zoom levels only partially load or not at all, after a short time it appears to stop loading completely on all zoom levels, one possible cause I thought of is bandwidth, I'm limited to about 3mbps down which may not be quite enough to load the map easily, but even with the follow mode off  it doesn't load at all no matter how long I wait.

[AviTab.log](https://github.com/fpw/avitab/files/1974920/AviTab.log)

**Comment by Chryseus** [comment]
No trouble loading it there, all the zoom levels in the area load fully in about 5 seconds, I'll have a see what exactly it's doing with wireshark and report back.

**Comment by Chryseus** [comment]
I seem to be unable to replicate the problem now, I've had it happen twice before so I'll close this for now until I'm able to gather more information.

**Comment by fpw** [comment]
Someone else reported the same on the forum, the error was also in a small timeframe only. I believe OpenTopoMap just had a short downtime.
