### ISSUE TITLE
Can't make windows package

### ISSUE THREAD

**Issue by mgateno** [fpw/avitab#92]
I cloned the repo and installed al the MSYS2 environment. I can successfully run ./setup.sh until the very end and then this happens: 

Making install in port
make[1]: Entering directory '/d/GitHub/avitab/lib/libtiff/port'
source='dummy.c' object='dummy.lo' libtool=yes \
DEPDIR=.deps depmode=none /bin/sh ../config/depcomp \
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../libtiff     -fPIC -Wall -W -c -o dummy.lo dummy.c
/bin/sh: ../config/depcomp: No such file or directory
make[1]: *** [Makefile:438: dummy.lo] Error 127
make[1]: Leaving directory '/d/GitHub/avitab/lib/libtiff/port'
make: *** [Makefile:546: install-recursive] Error 1
Failed
Running CMake...
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/GitHub/avitab/build
Select next step...
1. Make AviTab-Standalone
2. Make avitab-plugin
3. Nothing
2
Making avitab_plugin...
make: *** No rule to make target 'avitab_plugin'.  Stop.

Marco@NC-0720 MINGW64 /d/GitHub/avitab
$

Can you please let me know what I'm missing? Thanks

**Comment by fpw** [comment]
Hi,

that sounds like one of the dependencies was moved into a different MSYS package. It seems that depcomp can't be found, that should be part of the libtool package. Can you double check if that's installed?

**Comment by arturzx** [comment]
> I cloned the repo and installed al the MSYS2 environment. I can successfully run ./setup.sh until the very end and then this happens:
> 
> Making install in port
> make[1]: Entering directory '/d/GitHub/avitab/lib/libtiff/port'
> source='dummy.c' object='dummy.lo' libtool=yes
> DEPDIR=.deps depmode=none /bin/sh ../config/depcomp
> /bin/sh ../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I../libtiff -fPIC -Wall -W -c -o dummy.lo dummy.c
> /bin/sh: ../config/depcomp: No such file or directory
> make[1]: *** [Makefile:438: dummy.lo] Error 127
> make[1]: Leaving directory '/d/GitHub/avitab/lib/libtiff/port'
> make: *** [Makefile:546: install-recursive] Error 1
> Failed
> Running CMake...
> -- The C compiler identification is GNU 10.2.0
> -- The CXX compiler identification is GNU 10.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: D:/msys64/mingw64/bin/cc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: D:/msys64/mingw64/bin/c++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: D:/GitHub/avitab/build
> Select next step...
> 
> 1. Make AviTab-Standalone
> 2. Make avitab-plugin
> 3. Nothing
>    2
>    Making avitab_plugin...
>    make: *** No rule to make target 'avitab_plugin'.  Stop.
> 
> Marco@NC-0720 MINGW64 /d/GitHub/avitab
> $
> 
> Can you please let me know what I'm missing? Thanks

I have the same error and found workaround for this (have no time to dig what causes this problem):
ln -s -f /usr/share/automake/1.14/depcomp build-third/libtiff/config

Probably using --disable-dependency-tracking as libtiff configure option works too.
