### ISSUE TITLE
Flickering when using Vulkan on AMD GPUs

### ISSUE THREAD

**Issue by kubefrog** [fpw/avitab#98]
Avitab will flicker when "use Vulkan for faster rendering" option is enabled, rendering it unusable

**Comment by fpw** [comment]
Hi,

according to LR, this is actually a bug in AMD's driver and affects other plugins as well. Unfortunately I can't do anything about it. See here: https://forums.x-plane.org/index.php?/forums/topic/218997-vulkan-flickering/
